spring:
  application:
    name: provider
  cloud:
    zookeeper:
      connectString: 10.190.3.172:5888

server:
  port: 0


#eureka:  #默认关闭
#  client:
#    enabled: false
#
#
#management:
#  security:
#    enabled: fales
#---
#spring:
#  profiles: eureka
#
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://127.0.0.1:8082/eureka   #注册中心地址跟服务端一致






